apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-d105
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-d105@sha256:36e88152c347b4ec98ddb52301fb07e71cf432d54d1bca630b3491dbf6326a04
        name: my-nodejs
        resources: {}
status: {}
